version: 1.0

logging:
  level: "info"
  console: false # printing log to console is only supported in development mode

server_chain:
  id: "0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe"
  signature_scheme: "bls0chain"

port: 9082

handlers:
  rate_limit: 1 # 1 per second

miners:
  - http://one.devnet-0chain.net:31071
  - http://one.devnet-0chain.net:31072
  - http://one.devnet-0chain.net:31073
  - http://one.devnet-0chain.net:31074
  - http://one.devnet-0chain.net:31075
  - http://one.devnet-0chain.net:31076
  - http://one.devnet-0chain.net:31077
  - http://one.devnet-0chain.net:31078
  - http://one.devnet-0chain.net:31079
sharders:
  - http://one.devnet-0chain.net:31171
  - http://one.devnet-0chain.net:31172
  - http://one.devnet-0chain.net:31173
  - http://one.devnet-0chain.net:31174
  - http://one.devnet-0chain.net:31175
  - http://one.devnet-0chain.net:31176
  - http://one.devnet-0chain.net:31177
  - http://one.devnet-0chain.net:31178
  - http://one.devnet-0chain.net:31179
