version: 1.0

logging:
  level: "info"
  console: false # printing log to console is only supported in development mode

server_chain:
  id: "0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe"
  signature_scheme: "bls0chain"

port: 9082

handlers:
  rate_limit: 1 # 1 per second

miners:
  - http://one.devnet-0chain.net:31071
  - http://one.devnet-0chain.net:31072
  - http://one.devnet-0chain.net:31073
  - http://one.devnet-0chain.net:31074
sharders:
  - http://one.devnet-0chain.net:31171
  - http://one.devnet-0chain.net:31172
