version: 1.0

logging:
  level: "info"
  console: false # printing log to console is only supported in development mode

server_chain:
  id: "0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe"
  owner: "edb90b850f2e7e7cbd0a1fa370fdcc5cd378ffbec95363a7bc0e5a98b8ba5759"
  genesis_block:
    id: "ed79cae70d439c11258236da1dfa6fc550f7cc569768304623e8fbd7d70efae4"
  signature_scheme: "bls0chain"

port: 9082

allocation_default:
  data_shards: 2
  parity_shards: 2
  min_submit: 50
  min_confirmation: 50

miners:
  - http://one.devnet-0chain.net:31071
  - http://one.devnet-0chain.net:31072
  - http://one.devnet-0chain.net:31073
  - http://one.devnet-0chain.net:31074
  - http://one.devnet-0chain.net:31075
  - http://one.devnet-0chain.net:31076
  - http://one.devnet-0chain.net:31077
  - http://one.devnet-0chain.net:31078
  - http://one.devnet-0chain.net:31079
sharders:
  - http://one.devnet-0chain.net:31171
  - http://one.devnet-0chain.net:31172
  - http://one.devnet-0chain.net:31173
  - http://one.devnet-0chain.net:31174
  - http://one.devnet-0chain.net:31175
  - http://one.devnet-0chain.net:31176
  - http://one.devnet-0chain.net:31177
  - http://one.devnet-0chain.net:31178
  - http://one.devnet-0chain.net:31179
