version: 1.0

logging:
  level: "info"
  console: false # printing log to console is only supported in development mode

server_chain:
  id: "0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe"
  signature_scheme: "bls0chain"

port: 9082

handlers:
  rate_limit: 1 # 1 per second

block_worker: http://198.18.0.98:9091
clean_up_worker_minutes: 10
