name: Dockerize

on:
   push:
     branches: [ gitactionsfix ]

env:
  PROXY_REGISTRY: 0proxyreg/0proxy

jobs:
   dockerize_box:
       runs-on: ubuntu-20.04
       steps:
       - uses: actions/checkout@v2

       - name: Get the version
         id: get_version
         run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)    

           # - name: Login to Docker Hub
           #   uses: docker/login-action@v1
           #   with:
           #     username: ${{ secrets.DOCKERHUB_USERNAME }}
           #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Build zproxy
         run: |
            docker build -t $PROXY_REGISTRY:$TAG -f "$DOCKERFILE_PROXY" .
           # docker push $PROXY_REGISTRY:$TAG
         env:
           TAG: ${{ steps.get_version.outputs.VERSION }}
           DOCKERFILE_PROXY: "docker.local/Dockerfile"
